version: "3"

services:
  api:
    container_name: api
    build: 
      context: ./backend
      dockerfile: Dockerfile
    image: kk_api
    restart: always
    volumes: 
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules 
    ports:
      - "9000:3000"
        
  frontend:
    container_name: frontend
    build: 
      context: ./Frontend
      dockerfile: Dockerfile
    image: kk_frontend
    restart: always
    volumes: 
      - ./Frontend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "80:3000"
