version: "3"

services:
  api-service:
    container_name: api-service
    build: 
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    volumes: 
      - ./backend:/app
    ports:
      - "9000:3000"
    depends_on:
      - mongodb
      - redis
    links:
      - mongodb
    networks:
      - backend

  mongodb:
    image: mongo
    container_name: mongodb
    restart: unless-stopped
    volumes:
      - ./backend/data:/data/db
    ports:
      - "27017:27017"
    networks:
      - backend
    
  redis:
    container_name: redis
    image: redis:alpine
    volumes:
      - ./backend/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - backend 
    # environment:
    #   - REDIS_PORT_6379_TCP_ADDR:"backend:6379"  
    ports:
      - "6379:6379"

networks:
  backend:

volumes:
  redis-data:
