version: "3"

services:
  api:
    container_name: api
    build: 
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    volumes: 
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules 
    ports:
      - "9000:3000"
    networks:
      - kinkhorn

networks:
  kinkhorn:

volumes:
  redis-data:
