version: "3"

services:
  api:
    container_name: api
    build: 
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    volumes: 
      - ./backend:/app
    ports:
      - "9000:3000"
    depends_on:
      - mongodb
      - redis
    links:
      - mongodb
      - redis
    networks:
      - backend

  mongodb:
    image: mongo
    container_name: mongodb
    restart: unless-stopped
    volumes:
      - ./backend/data:/data/db
    expose: 
      - "27017"
    #ports:
    #  - "27017:27017"
    command: [--auth]
    networks:
      - backend
    
  redis:
    container_name: redis
    image: redis:alpine
    volumes:
      - ./backend/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - backend 
    command: redis-server --requirepass "QCY68NMK7KGNabfPg72P"
    # environment:
    #   - REDIS_PORT_6379_TCP_ADDR:"backend:6379"  
    expose: 
      - "6379"
    #ports:
    #  - "6379:6379"

networks:
  backend:

volumes:
  redis-data:
